name: Geranium
favicon: null
layout_spectrum: 0.22057417989708483
typography_spectrum: 0.07313279411755502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4164120627101511
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.8230142169632018
purpose: []
